name: 'Terraform'

on:
  push:
    branches:
      - 'test'
  pull_request:
    types: [closed]
    branches:
      - 'production'

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest

    # if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'production' 
    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set environment based on branch
      run: |
        if [ "${{github.event.pull_request.base.ref = 'production'}}"]
          echo "environment=production" >> $GITHUB_ENV
        elif [ "${{ github.ref }}" = "refs/heads/test" ]; then
          echo "environment=test" >> $GITHUB_ENV
        elif [ "${{ github.ref }}" = "refs/heads/production" ]; then
          echo "environment=production" >> $GITHUB_ENV
        else
          echo "environment=development" >> $GITHUB_ENV
        fi

    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.7.5
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: "./terraform"
        
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.7.5
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"

    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.7.5
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./terraform"
        
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.7.5
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./terraform"
        tf_actions_extra_args: '-out=tfplan'

    - name: Terraform Apply
      if: github.ref == 'refs/heads/test' || github.ref == 'refs/heads/production'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.7.5
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./terraform"